language: java

jdk:
  - oraclejdk8
  
cache:
    directories:
    - $HOME/.m2  

branches:
  only:
  - master
  
services:
  - cassandra

notifications:
  email:
  - enes.acikoglu@gmail.com

script: mvn clean install